"""Async sandbox tool adapter for AgentScope."""
import logging
import functools
from agentscope.message import TextBlock
from agentscope.tool import ToolResponse
from mcp.types import CallToolResult
from agentscope.mcp import MCPClientBase

logger = logging.getLogger(__name__)


def async_sandbox_tool_adapter(func):
    """
    Async Sandbox Tool Adapter.

    Wraps an async sandbox tool function so that its output is always converted
    into a ToolResponse object, which is required by the Toolkit.

    This adapter preserves the original function signature and docstring
    so that JSON schemas can be correctly generated by the Toolkit.

    Args:
        func: Original async sandbox tool function (may return dict, string, etc.).

    Returns:
        A callable that produces ToolResponse instead of raw data.
    """

    @functools.wraps(func)
    async def wrapper(*args, **kwargs):
        try:
            res = await func(*args, **kwargs)
        except Exception as e:
            logger.warning(
                "沙箱工具调用失败  tool=%s  error=%s",
                func.__name__, e,
                exc_info=True,
            )
            return ToolResponse(
                content=[
                    TextBlock(
                        type='text',
                        text=f"Error executing tool: {str(e)}",
                    ),
                ],
            )

        if isinstance(res, ToolResponse):
            return res

        try:
            # Try to validate as CallToolResult first
            mcp_res = CallToolResult.model_validate(res)
            as_content = MCPClientBase._convert_mcp_content_to_as_blocks(
                mcp_res.content,
            )
            resp = ToolResponse(
                content=as_content,
                metadata=mcp_res.meta,
            )
            return resp
        except Exception as validation_error:
            # If validation fails, create ToolResponse directly from the result
            logger.debug(
                "tool=%s 返回值不是 CallToolResult，直接构造 ToolResponse  result_type=%s",
                func.__name__, type(res).__name__,
            )
            try:
                # Handle different result types
                if isinstance(res, str):
                    content_text = res
                elif isinstance(res, dict):
                    # Try to extract content from common dictionary structures
                    if 'content' in res:
                        content_text = str(res['content'])
                    elif 'stdout' in res:
                        content_text = str(res['stdout'])
                    else:
                        content_text = str(res)
                else:
                    content_text = str(res)

                resp = ToolResponse(
                    content=[TextBlock(type='text', text=content_text)],
                    metadata=res if isinstance(res, dict) else None,
                )
                return resp
            except Exception as conversion_error:
                logger.warning(
                    f"Failed to create ToolResponse from result. "
                    f"Function: {func.__name__}, Result: {res!r}, Error: {conversion_error}",
                    exc_info=True,
                )
                return ToolResponse(
                    content=[TextBlock(type='text', text=f"Error converting result: {str(conversion_error)}")],
                )

    return wrapper